version: '3.8'
services:
  app:
    image: task2-app:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    networks:
      - app_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

networks:
  app_network:
