apiVersion: v1
entries:
  my-app-chart:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2025-01-04T10:00:16.674135034+03:00"
    description: A Helm chart for Kubernetes
    digest: 53cd2ed39d34f2ee464ec1de1b7dd0bdf074cf484bd744d6c03a10e3731f9e9e
    name: my-app-chart
    type: application
    urls:
    - my-app-chart-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-01-04T10:00:16.669749477+03:00"
    description: A Helm chart for Kubernetes
    digest: 6b32bf749be5d9e4722196e2ac4cbc53c64b0e4462e222977d74f0fa9bb832c1
    name: my-app-chart
    type: application
    urls:
    - my-app-chart-1.0.0.tgz
    version: 1.0.0
generated: "2025-01-04T10:00:16.665038073+03:00"
